### ISSUE TITLE
Error in running the code

### ISSUE THREAD

**Issue by PestyVesty** [ctjacobs/sudoku-genetic-algorithm#1]
The following error occur when running the code with python 2 and 3.

Traceback (most recent call last):
  File "/Desktop/sudoku.py", line 487, in <module>
    solution = s.solve()
  File "/Desktop/sudoku.py", line 377, in solve
    self.population.seed(Nc, self.given)
  File "/Desktop/sudoku.py", line 64, in seed
    self.update_fitness()
  File "/Desktop/sudoku.py", line 73, in update_fitness
    candidate.update_fitness()
  File "/Desktop/sudoku.py", line 108, in update_fitness
    column_count[self.values[i][j]-1] += 1  # ...Update list with occurrence of a particular number.
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by superk007** [comment]
I am getting same errors while running the code... Can you please help me on how to remove them?

**Comment by PestyVesty** [comment]
I didn’t use his code and implemented my own

**Comment by superk007** [comment]
please share your code if possible

**Comment by PestyVesty** [comment]
It’s an assignment, and if I remember correctly the genetic algorithm still
doesn’t solve the problem. I did identify what needs to be done but never
got around to it, u sure you still want it? Personally I think it’s not
well coded

**Comment by superk007** [comment]
okay...thanks
